### ISSUE TITLE
Could not download configuration from tungstenfabric to vMX

### ISSUE THREAD

**Issue by ljyfree** [tnaganawa/tungstenfabric-docs#1]
Hi tnaganawa
    This is Johnny Liu, who was researching how to download configuration via netconf from tungstenfabric(deployed with k8s) to Juniper's MX switch(vMX18.2R2.6 in EVE-NG).
    I followed the instruction from http://nakadaisuke.blogspot.com/2018/08/how-to-configure-contrailtungstenfabric.html but no configuration was download, even no netconf packet captured by tcpdump. 
    The print info as followes:
04/15/2020 01:57:34 AM [contrail-device-manager] [WARNING]: No features found for mx3(8c33b946-de4a-4a44-ab4d-abe40a3d803c)
04/15/2020 01:57:34 AM [contrail-device-manager] [WARNING]: It is not recommended to use 'get' or 'multiget' pycassa methods. It's better to use 'xget' or 'get_range' methods due to thrift limitations
04/15/2020 01:57:34 AM [contrail-device-manager] [WARNING]: Could not push config to the device: 8c33b946-de4a-4a44-ab4d-abe40a3d803c, mx3; Fabric Object not yet available for this Physical Router

   Any suggestion?

**Comment by ljyfree** [comment]
The release of tungstenfabric should be R5.0.1 since I pull the docker image from https://hub.docker.com/r/opencontrailnightly/ ,which was updated recently.

**Comment by tnaganawa** [comment]
Hi, Johnny,

Could you try this knob in /etc/contrail/common_config.env?
 DEVICE_MANAGER__DEFAULTS__push_mode=0
This feature is disabled by default in favor of ansible plugin, after 5.0.x, and this knob can be used to enable this.

https://github.com/tnaganawa/tungstenfabric-docs/blob/master/TungstenFabricPrimer.md#device-manager

**Comment by ljyfree** [comment]
Hi Tnaganawa

   Set as you suggest as followes:
```
[root@master01 ~]# cat /etc/contrail/common_config.env 
KUBERNETES_API_SERVER=192.168.122.177
TTY=True
ANALYTICSDB_NODES=192.168.122.177
ANALYTICS_SNMP_ENABLE=False
STDIN_OPEN=True
WEBUI_NODES=192.168.122.177
CONTROLLER_NODES=192.168.122.177
KUBERNETES_API_NODES=192.168.122.177
ANALYTICS_NODES=192.168.122.177
ANALYTICSDB_ENABLE=True
CONFIGDB_NODES=192.168.122.177
ANALYTICS_ALARM_ENABLE=False
CLOUD_ORCHESTRATOR=kubernetes
CONTROL_NODES=192.168.122.177
KUBEMANAGER_NODES=192.168.122.177
CONFIG_NODES=192.168.122.177
CONTRAIL_VERSION=1912-latest
DEVICE_MANAGER__DEFAULTS__push_mode=0
[root@master01 ~]# 
```

There was no change even if 
- remove/add physical router
- change role among None/Spine/Leaf
- restart docker contrail-controller-config-devicemgr and repeate operations above

Still print message as follows:
```
04/16/2020 10:36:39 PM [contrail-device-manager] [WARNING]: No features found for MX3(26cf72b2-0037-4710-b38c-83afa2baeeb3)
04/16/2020 10:36:39 PM [contrail-device-manager] [WARNING]: Could not push config to the device: 26cf72b2-0037-4710-b38c-83afa2baeeb3, MX3; Fabric Object not yet available for this Physical Router
```

I deployed TF with k8s according to https://tungstenfabric.org.cn/wiki/pages/viewpage.action?pageId=1704003 , whose steps described in English, except replase "hub.juniper.net" with "opencontrailnightly"

TF WebUI is different with Contrail Command so parts of steps could not be processed according to https://www.juniper.net/documentation/en_US/contrail5.0/topics/concept/using-device-manager-netconf-contrail.html 

Any suggestion?

**Comment by ljyfree** [comment]
Add  screenshots
![physical_router](https://user-images.githubusercontent.com/13234976/79527270-b730c600-8099-11ea-81d3-eb0b55bbc289.png)
![bgp_router](https://user-images.githubusercontent.com/13234976/79527277-bbf57a00-8099-11ea-8ec1-b413a40a77c9.png)

**Comment by tnaganawa** [comment]
Hi, Johnny,

Thanks for the detail.
Could you also try those commands? It will recreate config containers, including device-manager.

docker-compose -f /etc/contrail/config/docker-compose.yaml down
docker-compose -f /etc/contrail/config/docker-compose.yaml up -d

Best Regards,

**Comment by ljyfree** [comment]
It works to call juniper_conf.py!

Thanks.
BTW, where could I submit issue for TF?  I found something was not correct.

**Comment by tnaganawa** [comment]
Hi, Johnny,

Glad to hear that :)

To report some issue, this jira can be used.
https://tungsten.io/community/
https://jira.tungsten.io/projects/TFB/issues/TFB-15?filter=allopenissues


Best Regards,
///
Tatsuya
