### ISSUE TITLE
About evpn vxlan

### ISSUE THREAD

**Issue by noobcoderT** [tnaganawa/tungstenfabric-docs#8]
Hi, tnaganawa,

I have followed your instructions about evpn/vxlan integration with TF. It helps much, and I have make it success to use l2vni and l3vni.

But I'm still confused about the floating ip function using evpn/vxlan.

I know it works well to use bgp l3vpn and mpls over gre encapsulation for floating ip. But I want to know if it is possible to get it work with evpn/vxlan.

Can you give me some suggestion?
Thanks.

**Comment by tnaganawa** [comment]
Hi,
glad to hear that EVPN / VXLAN feature worked.

Unfortunately, I personally haven't tried VXLAN and floating ip combination .. :(

Hopefully some upstream folks have more idea.
https://tungstenfabric.slack.com/

**Comment by noobcoderT** [comment]
> Hi,
> glad to hear that EVPN / VXLAN feature worked.
> 
> Unfortunately, I personally haven't tried VXLAN and floating ip combination .. :(
> 
> Hopefully some upstream folks have more idea.
> https://tungstenfabric.slack.com/

Thanks, I will check that.
